### ISSUE TITLE
Задание по словарям - стиль

### ISSUE THREAD

**Issue by Kreisfahrer** [logicandgit/courses#1]
![image](https://cloud.githubusercontent.com/assets/5236540/19576367/6ccd1584-971b-11e6-8ad4-ecb2238cfd1a.png)

**Comment by Kreisfahrer** [comment]
1 - словарь в столбик
2 - название не совсем корректное
3 - можно было проще

Так больше ничего и не нашел 👍

**Comment by logicandgit** [comment]
Issue was fixed
